name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    uses: bertie-mc/bertie-ci/.github/workflows/build-mod.yml@v3.0.1

  client:
    needs: build
    uses: bertie-mc/bertie-ci/.github/workflows/client.yml@v3.0.1
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
