name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    uses: bertie-mc/bertie-ci/.github/workflows/build-mod.yml@v3.8.0

  unit-test:
    uses: bertie-mc/bertie-ci/.github/workflows/unit-test.yml@v3.8.0

  client-test:
    needs: build
    uses: bertie-mc/bertie-ci/.github/workflows/client-test.yml@v3.8.0
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      success-marker: WITHERED_HEARTS_GUI_MIXIN_OK
